#!/bin/bash

if ! command -v xdotool 2>/dev/null >/dev/null; then echo "xdotool not found. Install it"; fi
if ! command -v chromium 2>/dev/null >/dev/null; then echo "chromium not found. Install it"; fi
if ! command -v xmodmap 2>/dev/null >/dev/null; then echo "xmodmap not found. Install it"; fi
if ! command -v xset 2>/dev/null >/dev/null; then echo "xset not found. Install it"; fi

xset dpms 0 0 0
xset s noblank
xset s off
xset -dpms

while [ 1 ]; do
	xmodmap -e "keycode 67 = F6"
        xmodmap -e "keycode 70 = F3"

        chromium --password-store=basic --kiosk http://localhost:8999/
done
